### ISSUE TITLE
Value is not a valid number: NaN

### ISSUE THREAD

**Issue by reslear** [XanderD99/strapi-prometheus#28]
How to avoid this mistake? 

```
/opt/node_modules/.pnpm/prom-client@15.1.3/node_modules/prom-client/lib/histogram.js:237
			throw new TypeError(
			^
Value is not a valid number: NaN
    at /opt/node_modules/.pnpm/prom-client@15.1.3/node_modules/prom-client/lib/histogram.js:237:10
    at Histogram.observeWithoutExemplar (/opt/node_modules/.pnpm/prom-client@15.1.3/node_modules/prom-client/lib/histogram.js:74:54)
    at ServerResponse.<anonymous> (/opt/node_modules/.pnpm/strapi-prometheus@2.1.0_@strapi+sdk-plugin@5.2.7_@swc+helpers@0.5.13_@types+node@20.17.3_ters_a2bjtfecpiujqnuivnehsu6loy/node_modules/strapi-prometheus/dist/server/index.js:107:34)
    at /otel-auto-instrumentation-nodejs/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:55
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AsyncLocalStorageContextManager.with (/otel-auto-instrumentation-nodejs/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at ServerResponse.contextWrapper (/otel-auto-instrumentation-nodejs/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:32)
    at Object.onceWrapper (node:events:633:28)
    at ServerResponse.emit (node:events:531:35)
    at ServerResponse.emit (node:domain:488:12)
Node.js v20.18.0
```

**Comment by XanderD99** [comment]
Could you give a bit more context when or where this happened. I can't seem to find or replicate the issue

**Comment by reslear** [comment]
I caught it while editing field placement.  

https://github.com/user-attachments/assets/175d375e-99f7-42ab-b7e5-39aeb1781bee


```
[2024-12-09 17:41:54.506] http: PUT /content-manager/content-types/api::app-locale.app-locale/configuration (206 ms) 200
/Users/admin/Documents/dev/content-api/node_modules/.pnpm/prom-client@15.1.3/node_modules/prom-client/lib/histogram.js:237
                        throw new TypeError(
                        ^

TypeError: Value is not a valid number: NaN
    at /Users/admin/Documents/dev/content-api/node_modules/.pnpm/prom-client@15.1.3/node_modules/prom-client/lib/histogram.js:237:10
    at Histogram.observeWithoutExemplar (/Users/admin/Documents/dev/content-api/node_modules/.pnpm/prom-client@15.1.3/node_modules/prom-client/lib/histogram.js:74:54)
    at ServerResponse.<anonymous> (/Users/admin/Documents/dev/content-api/node_modules/.pnpm/strapi-prometheus@2.2.0_@strapi+sdk-plugin@5.2.7_@swc+helpers@0.5.13_@types+node@20.17.7_ters_s6foulzmpzqf7iapdnmxxi5q4m/node_modules/strapi-prometheus/dist/server/index.js:107:34)
    at Object.onceWrapper (node:events:633:28)
    at ServerResponse.emit (node:events:531:35)
    at ServerResponse.emit (node:domain:488:12)
    at onFinish (node:_http_outgoing:1031:10)
    at afterWrite (node:internal/streams/writable:708:5)
    at afterWriteTick (node:internal/streams/writable:694:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v20.17.0
```

**Comment by reslear** [comment]
@XanderD99 Great, congratulations, could you release it ?

**Comment by XanderD99** [comment]
Should be released :)
